import { Activity, Gauge, Thermometer, Zap } from 'lucide-react';
import type { ReactNode } from 'react';
import { memo } from 'react';
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Tick } from '../types';
const tooltipStyle = { backgroundColor:'#111a2a', border:'1px solid #2a3850', borderRadius:4, color:'#dce5f1', fontSize:10 };
function ChartCard({ title, icon, children, legend }: { title:string; icon:ReactNode; children:ReactNode; legend:ReactNode }) {
  return <section className="panel min-w-0 p-3"><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-2 text-[10px] font-semibold text-slate-300">{icon}{title}</div><div className="flex gap-3">{legend}</div></div>{children}</section>;
}
const Leg = ({ color, label, dashed=false }: {color:string;label:string;dashed?:boolean}) => <span className="flex items-center gap-1 text-[8px] text-slate-500"><i className="inline-block w-3 border-t" style={{borderColor:color,borderStyle:dashed?'dashed':'solid'}}/>{label}</span>;
const chartProps = { margin:{top:2,right:4,bottom:0,left:-17} };
function ChartTooltip({ active, payload, label }: any) {
  if (!active || !payload?.length) return null;
  return <div style={tooltipStyle} className="px-2 py-1.5"><div className="mb-1 text-slate-500">{new Date(label).toLocaleTimeString()}</div>{payload.map((p:any)=><div key={p.dataKey} style={{color:p.color}}>{p.name}: {Number(p.value).toFixed(2)}</div>)}</div>;
}
export const TelemetryCharts = memo(function TelemetryCharts({ history, tick }: { history: Tick[]; tick?: Tick }) {
  const danger = tick?.health.status === 'CRITICAL'; const primary = danger ? '#EF4444' : '#38BDF8';
  const data = history.map(t=>({time:Date.parse(t.timestamp), vibration:t.telemetry.vibration_rms_mm_s, crest:t.telemetry.vibration_crest_factor, temp:t.telemetry.temperature_c, rate:t.telemetry.temp_rate_c_per_min, current:t.telemetry.motor_current_a, rpm:t.telemetry.spindle_rpm, volatility:t.telemetry.rpm_volatility}));
  const latest = tick?.telemetry;
  return <div className="space-y-2" data-testid="panel-telemetry">
    <ChartCard title="Vibration · ISO 10816-3" icon={<Activity size={13} className={danger?'text-red-400':'text-sky-400'}/>} legend={<><Leg color={primary} label="RMS mm/s"/><Leg color="#8B5CF6" label="Crest factor"/><Leg color="#F59E0B" label="ISO threshold" dashed/></>}>
      <ResponsiveContainer width="100%" height={115}><LineChart data={data} {...chartProps}><CartesianGrid stroke="#1c293b" strokeDasharray="2 4" vertical={false}/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={(v)=>new Date(v).toLocaleTimeString([],{minute:'2-digit',second:'2-digit'})} tick={{fill:'#627188',fontSize:8,fontFamily:'DM Mono'}} axisLine={false} tickLine={false} minTickGap={36}/><YAxis yAxisId="left" tick={{fill:'#627188',fontSize:8}} axisLine={false} tickLine={false} width={31}/><YAxis yAxisId="right" orientation="right" tick={{fill:'#627188',fontSize:8}} axisLine={false} tickLine={false} width={27}/><Tooltip content={<ChartTooltip/>}/><ReferenceLine yAxisId="left" y={2.8} stroke="#F59E0B" strokeDasharray="4 4"/><ReferenceLine yAxisId="left" y={4.5} stroke="#EF4444" strokeDasharray="4 4"/><Line yAxisId="left" dataKey="vibration" name="RMS" stroke={primary} dot={false} strokeWidth={1.8} isAnimationActive={false}/><Line yAxisId="right" dataKey="crest" name="Crest" stroke="#8B5CF6" dot={false} strokeWidth={1.3} isAnimationActive={false}/></LineChart></ResponsiveContainer>
    </ChartCard>
    <ChartCard title="Thermal · temperature + dT/dt" icon={<Thermometer size={13} className={danger?'text-red-400':'text-amber-400'}/>} legend={<><Leg color={danger?'#EF4444':'#F59E0B'} label="°C"/><Leg color="#38BDF8" label="dT/dt °C/min"/></>}>
      <ResponsiveContainer width="100%" height={105}><LineChart data={data} {...chartProps}><CartesianGrid stroke="#1c293b" strokeDasharray="2 4" vertical={false}/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={(v)=>new Date(v).toLocaleTimeString([],{minute:'2-digit',second:'2-digit'})} tick={{fill:'#627188',fontSize:8,fontFamily:'DM Mono'}} axisLine={false} tickLine={false} minTickGap={36}/><YAxis yAxisId="left" tick={{fill:'#627188',fontSize:8}} axisLine={false} tickLine={false} width={31}/><YAxis yAxisId="right" orientation="right" tick={{fill:'#627188',fontSize:8}} axisLine={false} tickLine={false} width={27}/><Tooltip content={<ChartTooltip/>}/><Line yAxisId="left" dataKey="temp" name="Temperature °C" stroke={danger?'#EF4444':'#F59E0B'} dot={false} strokeWidth={1.8} isAnimationActive={false}/><Line yAxisId="right" dataKey="rate" name="dT/dt" stroke="#38BDF8" dot={false} strokeWidth={1.3} isAnimationActive={false}/></LineChart></ResponsiveContainer>
    </ChartCard>
    <ChartCard title="Power & Drive · current + RPM" icon={<Zap size={13} className={danger?'text-red-400':'text-emerald-400'}/>} legend={<><Leg color={primary} label="A"/><Leg color="#10B981" label="RPM"/></>}>
      <ResponsiveContainer width="100%" height={105}><LineChart data={data} {...chartProps}><CartesianGrid stroke="#1c293b" strokeDasharray="2 4" vertical={false}/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={(v)=>new Date(v).toLocaleTimeString([],{minute:'2-digit',second:'2-digit'})} tick={{fill:'#627188',fontSize:8,fontFamily:'DM Mono'}} axisLine={false} tickLine={false} minTickGap={36}/><YAxis yAxisId="left" tick={{fill:'#627188',fontSize:8}} axisLine={false} tickLine={false} width={31}/><YAxis yAxisId="right" orientation="right" tick={{fill:'#627188',fontSize:8}} axisLine={false} tickLine={false} width={33}/><Tooltip content={<ChartTooltip/>}/><Line yAxisId="left" dataKey="current" name="Current A" stroke={primary} dot={false} strokeWidth={1.8} isAnimationActive={false}/><Line yAxisId="right" dataKey="rpm" name="Spindle RPM" stroke="#10B981" dot={false} strokeWidth={1.3} isAnimationActive={false}/></LineChart></ResponsiveContainer>
    </ChartCard>
    <section className="panel flex flex-wrap items-center gap-x-5 gap-y-3 px-3 py-2.5"><div className="min-w-[170px] flex-1"><div className="mb-1.5 flex justify-between text-[9px]"><span className="flex items-center gap-1 text-slate-400"><Gauge size={12}/> WORKLOAD RATIO</span><span data-testid="text-workload" className="mono text-slate-200">{latest?.workload_pct.toFixed(1) ?? '—'}%</span></div><div className="h-1.5 overflow-hidden rounded bg-[#1b2637]"><div className="h-full rounded bg-sky-400 transition-all" style={{width:`${latest?.workload_pct ?? 0}%`}}/></div></div><div className="border-l border-[#253147] pl-4"><div className="panel-title text-[8px]">OPERATING HOURS</div><div data-testid="text-operating-hours" className="mono mt-1 text-[12px] text-slate-200">{latest?.operating_hours.toLocaleString(undefined,{maximumFractionDigits:1}) ?? '—'} <small className="text-slate-500">hrs</small></div></div><div className="border-l border-[#253147] pl-4"><div className="panel-title text-[8px]">SERVICE AGE</div><div data-testid="text-service-age" className="mono mt-1 text-[12px] text-slate-200">{latest?.service_age_hrs.toFixed(0) ?? '—'} <small className="text-slate-500">hrs</small></div></div><div className="border-l border-[#253147] pl-4"><div className="panel-title text-[8px]">RPM VOLATILITY</div><div className="mono mt-1 text-[12px] text-sky-300">{latest?.rpm_volatility.toFixed(3) ?? '—'}</div></div></section>
  </div>;
});